# Generated by Django 5.0.4 on 2024-04-30 05:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedToken',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.CharField(max_length=355, unique=True)),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='attendance',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Attendance'),
        ),
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Emergency contact'),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Emergency contact Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Home Language'),
        ),
        migrations.AddField(
            model_name='user',
            name='leaves',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Leaves Per Year'),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Middle Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_mail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Parent Email ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_type',
            field=models.CharField(blank=True, choices=[('part_time', 'Part Time'), ('full_time', 'Full Time')], max_length=10, null=True, verbose_name='Employment Type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=8, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('driver', 'Driver'), ('other', 'Other')], max_length=8, null=True, verbose_name='Employee Type'),
        ),
    ]
