# Generated by Django 5.0.6 on 2024-05-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('driver', 'Driver'), ('other', 'Other')], default=1, max_length=8, verbose_name='User Type'),
            preserve_default=False,
        ),
    ]
